// <auto-generated />
using System;
using ExpenseTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTracker.Migrations
{
    [DbContext(typeof(ExpenseTrackerDbContext))]
    [Migration("20251122114535_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTracker.Expenses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedTimeStamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 150.75m,
                            Category = "Food",
                            CreatedTimeStamp = new DateTimeOffset(new DateTime(2025, 11, 20, 19, 45, 35, 158, DateTimeKind.Unspecified).AddTicks(2420), new TimeSpan(0, 8, 0, 0, 0)),
                            Title = "Grocery Shopping"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 60.00m,
                            Category = "Utilities",
                            CreatedTimeStamp = new DateTimeOffset(new DateTime(2025, 11, 12, 19, 45, 35, 158, DateTimeKind.Unspecified).AddTicks(2460), new TimeSpan(0, 8, 0, 0, 0)),
                            Title = "Electricity Bill"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 30.50m,
                            Category = "Entertainment",
                            CreatedTimeStamp = new DateTimeOffset(new DateTime(2025, 11, 17, 19, 45, 35, 158, DateTimeKind.Unspecified).AddTicks(2463), new TimeSpan(0, 8, 0, 0, 0)),
                            Title = "Movie Night"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
